### ISSUE TITLE
Current symlink prefers milestones to releases.

### ISSUE THREAD

**Issue by spencergibb** [spring-io/autoln#1]
For the spring cloud release train Hoxton.SR8 is current. Under java autoln it's 2020.0.0-M4

For spring cloud gateway current is 2.2.5.RELEASE, and java autoln it would be 3.0.0-M4

**Comment by rwinch** [comment]
This should now be fixed.

The first issue has tests here https://github.com/spring-io/autoln/commit/273815835eda169b493a3c98642daa82a74b77b4#diff-fa9a018d0a7b781ec070e2e4341333a3701ad0f78e00057eadca879c9c373e76R141

The second is fixed here https://github.com/spring-io/autoln/commit/cc87bd1ca45222861d71905887ff088ef7deedeb#diff-cdf13f1696f05d4926dbd90febbc57868b3b17115b54b226f603d534faafb9e3R152
