### ISSUE TITLE
Clean existing content when updating snapshots

### ISSUE THREAD

**Issue by philwebb** [spring-io/autoln#2]
Currently any existing content is not cleaned when new snapshots are deployed. This can make it hard to find some bugs. For example, Spring Boot had a recent issue due to a missing CSS but we didn't spot it because the previous version was still in the folder.

**Comment by rwinch** [comment]
I'm not sure I understand. It sounds like you are asking `autoln` to remove existing files before linking to a folder?

**Comment by trevormarshall** [comment]
`autoln` does not download and unzip the docs distributions, it only does the linking. 
Those tasks are still performed by Giorgio's script in the [Pivotal private repo](https://github.com/pivotal/spring-docs-www-conf/tree/master/docs/autorepo_script)

**Comment by rwinch** [comment]
Agreed @trevormarshall I don't think it is even possible for autoln to remove content because it has no understanding of what is new or old. I'm going to go ahead and close this, but if @philwebb disagrees he can provide some more details.
